/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sazlm.vending_view.payment_menu;

/**
 *
 * @author ialex
 */
public class ConfirmationProductFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form i
     */
    public ConfirmationProductFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockProdukPlaceholder1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconItem = new javax.swing.JLabel();
        namaProduk = new javax.swing.JLabel();
        hargaProduk = new javax.swing.JLabel();
        stockProdukPlaceholder = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        plus = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        stockProdukLabel = new javax.swing.JLabel();

        stockProdukPlaceholder1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockProdukPlaceholder1.setForeground(new java.awt.Color(204, 204, 204));
        stockProdukPlaceholder1.setText("sisa stock:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iconItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        namaProduk.setFont(new java.awt.Font("Square721 BT", 1, 18)); // NOI18N
        namaProduk.setText("(nama produk)");

        hargaProduk.setFont(new java.awt.Font("Square721 BT", 0, 16)); // NOI18N
        hargaProduk.setText("(harga produk)");

        stockProdukPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockProdukPlaceholder.setForeground(new java.awt.Color(204, 204, 204));
        stockProdukPlaceholder.setText("sisa stock:");

        numLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numLabel.setText("0");

        plus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plusMousePressed(evt);
            }
        });

        minus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minus.setText("-");
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minusMousePressed(evt);
            }
        });

        stockProdukLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockProdukLabel.setForeground(new java.awt.Color(204, 204, 204));
        stockProdukLabel.setText("(num)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconItem, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaProduk)
                            .addComponent(hargaProduk))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(minus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plus)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(stockProdukPlaceholder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockProdukLabel)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaProduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaProduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockProdukPlaceholder)
                            .addComponent(stockProdukLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numLabel)
                            .addComponent(plus)
                            .addComponent(minus)))
                    .addComponent(iconItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMousePressed
        // TODO add your handling code here:
        
        String numFromLabel = numLabel.getText();
        int num = Integer.parseInt(numFromLabel);
        num++;
        numLabel.setText(num +"");
    }//GEN-LAST:event_plusMousePressed

    private void minusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMousePressed
        // TODO add your handling code here:
        String numFromLabel = numLabel.getText();
        int num = Integer.parseInt(numFromLabel);
        num--;
        numLabel.setText(num +"");
    }//GEN-LAST:event_minusMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationProductFrame().setVisible(true);
            }
        });
    }
    
    // Method to update the view of stock
    public void setStockItem(String stockInfo){
        stockProdukLabel.setText(stockInfo);
    }
    
    // Method to get updated stock
    public int getStockItem(){
        int stock = Integer.parseInt(stockProdukLabel.getText());
        return stock;
    }
    
    // Method to get Quantity from ui
    public int getQuantity(javax.swing.JLabel numLabel){
        String numFromLabel = numLabel.getText();
        int num = Integer.parseInt(numFromLabel);
        return num;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaProduk;
    private javax.swing.JLabel iconItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel namaProduk;
    private javax.swing.JLabel numLabel;
    private javax.swing.JLabel plus;
    private javax.swing.JLabel stockProdukLabel;
    private javax.swing.JLabel stockProdukPlaceholder;
    private javax.swing.JLabel stockProdukPlaceholder1;
    // End of variables declaration//GEN-END:variables
}
