/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sazlm.vending_controller;

public class App {
    public String getGreeting() {
        return "Hello jancuk!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
