/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sazlm.vending_controller;

import sazlm.vending_model.Machine;
import sazlm.vending_view.TerminalView;


public class App {
    public static void main(String[] args) {
        Machine vendingMachine = new Machine();
        TerminalView view = new TerminalView();

        System.out.println("Welcome to the Vending Machine!");

        while (true) {
            view.displayMenu();
            int choice = view.getChoiceInput();
            view.consumeNewLine();

            switch (choice) {
                case 1:
                    String productName = view.getProductNameInput();
                    vendingMachine.selectProduct(productName);
                    break;
                case 2:
                    int quantity = view.getQuantityInput();
                    vendingMachine.selectQuantity(quantity);
                    break;
                case 3:
                    int paymentAmount = view.getPaymentAmountInput();
                    vendingMachine.processPayment(paymentAmount);
                    break;
                case 4:
                    vendingMachine.completeTransaction();
                    break;
                case 5:
                    vendingMachine.checkBalance();
                    break;
                case 6:
                    vendingMachine.cancelTransaction();
                    break;
                case 7:
                    System.out.println("Exiting the Vending Machine. Goodbye!");
                    System.exit(0);
                    break;
                default:
                    view.displayMessage("Invalid choice. Please try again.");
            }

            view.displayCurrentState(
                vendingMachine.getCurrentState().toString(),
                vendingMachine.getSelectedProduct().toString(),
                vendingMachine.getSelectedQuantity()
            );
        }
        }
}



